# Generated by Django 4.2.10 on 2024-02-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phonecode', models.IntegerField()),
            ],
        ),
    ]
